### ISSUE TITLE
Can we bump to 8.5?

### ISSUE THREAD

**Issue by jakerella** [components/highlightjs#12]
Was released a couple weeks ago...

**Comment by RobLoach** [comment]
@jakearchibald If you send a Pull Request, then we could merge and tag quite easily :+1: .

**Comment by jakearchibald** [comment]
Wrong Jake I think!

**Comment by RobLoach** [comment]
@jakearchibald Haha, yup. That's what I get for using tab too much.... @jakerella .

**Comment by jakerella** [comment]
;) I'll try to get that done today...

**Comment by jakerella** [comment]
Question: Do you include all languages in your pack or just the "Common" ones as listed on the highlight.js site?

**Comment by jakerella** [comment]
Nevermind... I think I see, you use the Makefile to pull down the source, build a new pack, and copy over the styles. Please correct me if I'm wrong.

**Comment by RobLoach** [comment]
@jakerella Also added you as a maintainer too, so you could push these forwards in the future :+1: . Thanks a lot!
