### ISSUE TITLE
Using webpack/commonjs with minified throws 'hljs is not defined'

### ISSUE THREAD

**Issue by mpolichette** [components/highlightjs#15]
Am I the only one getting this error with the minified version when using webpack and commonjs requires?

The minified version seems to want to use `hljs` right from the window... which defeats the purpose of modular requires.  My system doesn't put `hljs` on the window and it means I can't use this package at all. 

:( 

Please let me know if this seems to be my issue only.

**Comment by tsl0922** [comment]
It should works for commonjs as described in [tools/build.js](https://github.com/isagalaev/highlight.js/blob/master/tools/build.js), which is used to build release files for this repo. The minified version works for me at node environment, node uses commonjs.

**Comment by edencore** [comment]
@mpolichette did you solve your problem? I have it too

**Comment by mpolichette** [comment]
I think I was able to solve this by using a webpack plugin which would
insert the hljs library on the local scope. I'm mobile right now, if you
need more help let me know and I'll look up the exact process.

**Comment by edencore** [comment]
@mpolichette thank you for your answer. I've found this issue: https://github.com/components/highlightjs/issues/21 . So, I just updated `highlightjs` and everything is okay now.

**Comment by RobLoach** [comment]
I'll close this for now. If you're still experiencing issues, let us know! :+1:
