### ISSUE TITLE
Does this include all Highlightjs Languages?

### ISSUE THREAD

**Issue by CrashyBang** [components/highlightjs#18]
Hey just checking, does this include all Highlightjs Languages or is it just the recommended 22?

**Comment by tylerlong** [comment]
Yes I think so.
Goto https://github.com/components/highlightjs/blob/master/highlight.pack.js
Search for `hljs.registerLanguage(`
At the moment it supports 135 languages.

**Comment by badlydrawnrob** [comment]
This is **exactly** what I've been searching for. My js is pretty useless and this works great for my usecase, which needs to be all on one html page! Great work :+1:

**Comment by RobLoach** [comment]
Thanks for the research on this! 9.2.0 is out now too. :+1:
