### ISSUE TITLE
[improvement suggetion] Highlightjs could do a better job for patches

### ISSUE THREAD

**Issue by yurivict** [components/highlightjs#28]
Please look at this patch in Phabricator: https://reviews.freebsd.org/differential/diff/11400/?revisionID=4603

It is .mk file, therefore all changed by patch areas are in 'make' syntax. Additionally, make's targets are in the 'shell' syntax.

Phabricator knows all this. And highlightjs only shows the added lines in green.

**Comment by tsl0922** [comment]
Hi yurivict , this repo does not accept issues or feature request for highlightjs, report this to the original repo: https://github.com/isagalaev/highlight.js
