### ISSUE TITLE
npm has 9.8 as latest version

### ISSUE THREAD

**Issue by eman1986** [components/highlightjs#40]
on npm it has 9.8 as the latest version, but this repo has it set as 9.10, could someone push it up to npm please? Thanks

**Comment by RobLoach** [comment]
If you submit a PR, we can publish it :+1:

**Comment by eman1986** [comment]
someone committed it already, someone just needs to push up the changes to npm

**Comment by RobLoach** [comment]
Ah, thanks. Done.
