### ISSUE TITLE
Not working in Google Chrome

### ISSUE THREAD

**Issue by egordorichev** [components/highlightjs#41]
Code is not being highlighted. No errors in console.
[_**live**_](https://egordorichev.github.io/blog/)

**Comment by tsl0922** [comment]
`hljs.initHighlightingOnLoad()` may not working with lazy loaded content, you can call `hljs.highlightBlock(node)` after the content is loaded.

BTW: this repo does not accept issues or feature request for highlightjs, report this to the original repo: https://github.com/isagalaev/highlight.js

**Comment by egordorichev** [comment]
Nah, moved `hljs.initHighlightingOnLoad();` to after load method. Now the code element gets `lang-c` class, but nothing is highlighted.
