### ISSUE TITLE
what does shim repo mean?

### ISSUE THREAD

**Issue by lessfish** [components/highlightjs#45]
I wonder what shim repo mean? I do not find any introduction, can anyone explain for me?

for instance, what's the difference between highlightjs here and [this one](https://github.com/isagalaev/highlight.js/)? thanks

**Comment by RobLoach** [comment]
It's a helper repository, to make it easier to consume into different package management systems. You could likely use highlightjs straight from the source, without needing this.

**Comment by hanzichi** [comment]
@RobLoach 
thanks for your reply. The shim one is compatiable to multiple package management systems, such as AMD, commonjs, broswerify and so on? Can I understand like this?

another question, why [the shim one](https://github.com/components/highlightjs/blob/master/highlight.pack.min.js)(514kb) is much much larger than the normal one(30~40kb)? thanks in advance!

**Comment by RobLoach** [comment]
Might include some addons to Highlight? Unsure. Feel free to submit a PR to update/fix as needed.
