### ISSUE TITLE
Publish 9.12.0 to npm

### ISSUE THREAD

**Issue by vinc** [components/highlightjs#46]
The repo has been bumped to 9.12.0 but the npm package is still at 9.10.0 https://www.npmjs.com/package/highlightjs

Would it be possible to update it? Cheers!

**Comment by RobLoach** [comment]
Dunzo! Thnaks for the ping. Also added youas a maintainer on the npm packge tooooo.

**Comment by tsl0922** [comment]
@RobLoach I didn't receive a message/email from npm, can you add me again, thanks.
