### ISSUE TITLE
Please update highlight.js dependency

### ISSUE THREAD

**Issue by marcoscaceres** [components/highlightjs#47]
Hi, just a friendly reminder to please update the hljs dependency :) 

Because the repos are published on npm with nearly identical names, we are getting reports like:
https://github.com/highlightjs/highlight.js/issues/1874

When possible, please republish with new version.

**Comment by yyyc514** [comment]
Ping.

If this is no longer maintained could we remove it from NPM or just point it to the official build on NPM of Highlight.js that is maintained by core?

**Comment by RobLoach** [comment]
Thanks for the ping! Looks like `highlight.js` is well maintained at this point. I'll update the current version, and stick a deprecation notice on it.

**Comment by RobLoach** [comment]
> This package has been deprecated
Author message:
Use the 'highlight.js' package instead https://npm.im/highlight.js
